# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the OpenQMC Project.

services:
  develop:
    build: .
    command: nix develop
    working_dir: /tmp/src
    volumes:
      - .:/tmp/src
    ports:
      - 8888:8888
