name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop -ic scripts/check-format.sh

  check-static-analyzer:
    name: Check static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop -ic cmake --preset unix
      - run: nix develop -ic scripts/check-lint.sh

  install:
    name: Install library
    needs:
      - check-formatting
      - check-static-analyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop -ic cmake --preset base -D CMAKE_INSTALL_PREFIX=install
      - run: nix develop -ic cmake --build --preset base --target install

      # Upload installation for example-config
      - uses: actions/upload-artifact@v3
        with: {name: install, path: "install"}

  example-config:
    name: Check config
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Download installation
      - uses: actions/download-artifact@v3
        with: {name: install, path: "install"}

      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop -ic cmake -S cmake/examples/config -B build -D CMAKE_INSTALL_PREFIX=install
      - run: nix develop -ic cmake --build build
      - run: nix develop -ic ./build/example-config

  example-submodule:
    name: Check submodule
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop -ic cmake -S cmake/examples/submodule -B build
      - run: nix develop -ic cmake --build build
      - run: nix develop -ic ./build/example-submodule

  example-include:
    name: Check include
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop -ic cmake -S cmake/examples/include -B build
      - run: nix develop -ic cmake --build build
      - run: nix develop -ic ./build/example-include

  test-unit:
    name: Run unit tests
    needs:
      - example-config
      - example-submodule
      - example-include
    strategy:
      matrix:
        build: [Release, Debug]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop -ic cmake --preset unix -D CMAKE_BUILD_TYPE=${{ matrix.build }}
      - run: nix develop -ic cmake --build --preset unix --target tests
      - run: nix develop -ic ctest --preset unix

  build-tools:
    name: Build tools library
    needs: test-unit
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, self-hosted]
        os: [ubuntu-latest, macos-latest]
        arch: [Scalar, SSE, AVX, ARM, GPU]
        build: [Release, Debug]
        exclude:
          - {os: ubuntu-latest, arch: ARM}
          - {os: ubuntu-latest, arch: GPU}
          - {os: macos-latest, arch: AVX}
          - {os: macos-latest, arch: ARM}
          - {os: macos-latest, arch: GPU}
          # - {os: self-hosted, arch: Scalar}
          # - {os: self-hosted, arch: SSE}
          # - {os: self-hosted, arch: AVX}
        include:
          - {os: ubuntu-latest, save: true}
          # - {os: self-hosted, save: true}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop -ic cmake --preset unix -D OPENQMC_ARCH_TYPE=${{ matrix.arch }} -D CMAKE_BUILD_TYPE=${{ matrix.build }}
      - run: nix develop -ic cmake --build --preset unix
      - run: nix develop -ic tar -czvf build.tar.gz build
        if: ${{ matrix.save }}

      # Upload tools build for test-generate
      - uses: actions/upload-artifact@v3
        with: {name: "${{ matrix.build }}-${{ matrix.arch }}", path: build.tar.gz}
        if: ${{ matrix.save }}

  pre-test-generate:
    name: Pre generate reference data
    needs: build-tools
    strategy:
      matrix:
        sampler: [pmj, sobol, lattice]
    runs-on: ubuntu-latest
    steps:
      # Download tools build
      - uses: actions/download-artifact@v3
        with: {name: Release-Scalar}

      - run: tar -xzvf build.tar.gz
      - run: ./build/src/tools/cli/generate ${{ matrix.sampler }} > data

      # Upload sample data for test-generate
      - uses: actions/upload-artifact@v3
        with: {name: "${{ matrix.sampler }}", path: data}

  test-generate:
    name: Run generate
    needs: pre-test-generate
    strategy:
      matrix:
        # os: [ubuntu-latest, self-hosted]
        os: [ubuntu-latest]
        arch: [Scalar, SSE, AVX, ARM, GPU]
        build: [Release, Debug]
        sampler: [pmj, sobol, lattice]
        exclude:
          - {os: ubuntu-latest, arch: ARM}
          - {os: ubuntu-latest, arch: GPU}
          # - {os: self-hosted, arch: Scalar}
          # - {os: self-hosted, arch: SSE}
          # - {os: self-hosted, arch: AVX}
    runs-on: ${{ matrix.os }}
    steps:
      # Download tools build
      - uses: actions/download-artifact@v3
        with: {name: "${{ matrix.build }}-${{ matrix.arch }}"}

      # Download sample data
      - uses: actions/download-artifact@v3
        with: {name: "${{ matrix.sampler }}"}

      - run: tar -xzvf build.tar.gz
      - run: ./build/src/tools/cli/generate ${{ matrix.sampler }} > output
      - run: diff output data
